### ISSUE TITLE
server not handling reconnection.

### ISSUE THREAD

**Issue by Abhinav-ark** [IAmRiteshKoushik/bluedis#1]
When I exit an existing connection using Ctrl + c and try to reconnect, I get this error.
![image](https://github.com/user-attachments/assets/94cb44e3-1797-4db5-b1fe-0664f8d4e6be)

These are the server logs.
![image](https://github.com/user-attachments/assets/b534ff2d-3742-492c-9a90-2d857b592e6b)

**Comment by IAmRiteshKoushik** [comment]
Will roll out a fix soon.

**Comment by IAmRiteshKoushik** [comment]
This has been fixed as of https://github.com/IAmRiteshKoushik/bluedis/commit/807c1e96c06cec24559b371f363a7521e6878d18
