### ISSUE TITLE
Project name already exists.

### ISSUE THREAD

**Issue by Abhinav-ark** [IAmRiteshKoushik/bluedis#2]
There is another project that already exists by the name of bluedis.
<https://github.com/ghanizadev/bluedis>

Affects SEO.

**Comment by IAmRiteshKoushik** [comment]
As this project was done with the primary intention of trying to learn about Redis internals and the Redis Specification Protocol, and this not being a long-term project which associates with Redis under any capacity, I don't see much point in renaming. However if you could suggest a better name then happy to migrate.
