### ISSUE TITLE
Exit command shuts the server down.

### ISSUE THREAD

**Issue by Abhinav-ark** [IAmRiteshKoushik/bluedis#3]
Executing `exit` command, shuts down the server.
![image](https://github.com/user-attachments/assets/18cfa64a-60f2-470b-9e87-9360266f0268)
Server logs:
![image](https://github.com/user-attachments/assets/5cedecad-ddc1-4f88-9b8c-02ddd92a5d89)

**Comment by Abhinav-ark** [comment]
Similar to #1.

**Comment by IAmRiteshKoushik** [comment]
Closing as duplicate to #1. Will fix #1
