### ISSUE TITLE
New ✨ Implement Cache Expiration for Data

### ISSUE THREAD

**Issue by eshwanthkartitr** [IAmRiteshKoushik/bluedis#5]
## Issue Description

Currently, there is no cache-invalidation strategy. We need to allow the user to be able to setup cache invalidation for every key-value pair entry they make. The `ttl` is to be used here but there must be some customization where this remains as an optional field.

## High Level Goals
- [ ] Implement OPTIONAL cache invalidation
- [ ] Make sure to add the changes like-wise to `aof.go` as it adds persistance to Bluedis.

As this project is a systems programming project, I would like to have a discussion before assigning this issue to anyone. Feel free to mention your approach here or send an email at `cb.en.u4cse22038@cb.students.amrita.edu` where we could connect better. 

Cheers 🍻

**Comment by eshwanthkartitr** [comment]
@IAmRiteshKoushik i would like to implement this

**Comment by IAmRiteshKoushik** [comment]
Hey @eshwanthkartitr can you write down a bit about how you are going to implement. Happy to assign it to you after we have discussed a bit on the implementation of this. Have added a bit of description as well to the issue.

**Comment by eshwanthkartitr** [comment]
Hi @IAmRiteshKoushik  I have some ideas for implementing the expiration mechanism. I'm thinking of using a map with struct(content , ttl , hasexpiry) This way, we can keep both permanent and expiring values in the same map without complicating things too much.
 I want to implement two methods - in handling set command which uses a background goroutine that periodically checks and cleans up expired keys  and in get commands checks expiry when a key is accessed.
Also I'll extend the SET command to handle an optional PX parameter for setting TTL, just like in Redis . I'll also add an EXPIRE command to update TTL for existing keys.

**Comment by IAmRiteshKoushik** [comment]
Sounds great da. Let's do it. Have assigned the issue to you @eshwanthkartitr . Further updates, let's discuss over WhatsApp.
